#!/bin/bash

if [ $SPIN ]; then
    REPO=~/src/github.com/shopify/shopify
else
    REPO=~/src/github.com/Shopify/shopify
fi

safe cd $REPO

# Hack to install if broken yet again...
(ripper-tags --help || gem install ripper-tags) > /dev/null 2>&1

CMD="ripper-tags -f TAGS -R -e components/ gems/ lib/"
echo "Running in background: $CMD"
$CMD &
